# Generated by Django 3.0.2 on 2020-01-23 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0002_auto_20200123_0259"),
        ("account", "0002_auto_20200122_0847"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True)),
                ("agreeCount", models.IntegerField(default=0)),
                ("disAgreeCount", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.Account",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.Videos"
                    ),
                ),
            ],
            options={"ordering": ["created"],},
        ),
    ]
