# Generated by Django 3.0.2 on 2020-01-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos", name="description", field=models.TextField(blank=True),
        ),
    ]
