# Generated by Django 3.0.2 on 2020-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(unique=True)),
                ("name", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["created"],},
        ),
    ]
