# Generated by Django 3.0.2 on 2020-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("google_id", models.CharField(blank=True, max_length=100)),
                ("user_name", models.CharField(blank=True, max_length=100)),
                (
                    "avatar",
                    models.CharField(
                        default="http://img.duoziwang.com/2019/05/08050202206333.jpg",
                        max_length=100,
                    ),
                ),
                ("fansLevel", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscribes", models.ManyToManyField(to="channels.Channels")),
            ],
            options={"ordering": ["created"],},
        ),
    ]
