# Generated by Django 3.0.2 on 2020-01-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="subscribes",
            field=models.ManyToManyField(blank=True, to="channels.Channels"),
        ),
    ]
